/* Extended keystrokes */
#define F1    59
#define ALTF1 104
#define F2    60
#define F3    61
#define F4    62
#define F5    63
#define F6    64
#define F7    65
#define F8    66
#define F9    67
#define F10   68
#define F11   133
#define F12   134
#define ALT_S 31
#define ALT_B 48
#define ALT_C 46
#define ALT_I 23
#define ALT_D 32
#define ALT_E 18
#define PGUP  73
#define PGDN  81
#define HOME  71
#define END   79
#define UP    72
#define RIGHT 77
#define LEFT  75
#define DOWN  80
#define INS   82
#define DEL   83

/* Normal keystrokes */
#define TAB    9
#define BS     8
#define ENTER 13
#define ESC   27





