// Auditable portability extraction. Original source is never modified.
import fs from "node:fs";
const original = fs.readFileSync("legacy/RESOLVE.CPP", "utf8");
let source = original
  .replace('#include "datascrn.hpp"', '#include "adapter.hpp"')
  .replace('#include "test.hpp"', '#include "fields.hpp"')
  .replace('#include "window.hpp"', "");
source = source.slice(0, source.indexOf("int weaponSearch_atkscrn()"));
source = source.replaceAll("NAN", "INVALID_NUMBER");
source = source.replace(
  "static float defineRandomGuyHits",
  "float defineRandomGuyHits",
);
source = source.replace(
  /if \(flag\)\s*\{[\s\S]*?else\s*memcpy\(tempData->readAddr\(0\),unitSet\[a\]->readAddr\(0\),tempData->getSize\(\)\);/,
  "*tempData = flag ? snapshots[a] : *unitSet[a];",
);
source = source.replaceAll("rand()%100", "portableRandom()%100");
source = source.replace(
  "for(i=0; i<numAtt; i++)",
  "lastAttackCount = numAtt;\n   for(i=0; i<numAtt; i++)",
);
source = source.replace(
  "numDef += defUnit[U_NM_N] - numDefSave;",
  "lastDamage = (long)(hitSave - hits);\n   numDef += defUnit[U_NM_N] - numDefSave;",
);
// Both versions use the same storage, process and RNG seams. Reference combat stays unchanged.
fs.writeFileSync("core/reference.cpp", source);
const start = source.indexOf("void initWeap()");
const end = source.indexOf("// Returns integer", start);
source =
  source.slice(0, start) +
  `void initWeap() {
    static std::array<Weapon, 100> storage{};
    static std::array<Weapon*, 100> pointers{};
    std::ifstream input("weapons.dat");
    if (!input) throw std::runtime_error("Cannot open weapons.dat");
    weapon = pointers.data(); numWeap = 0;
    std::string line;
    while (std::getline(input,line)) {
        if (line.empty() || line[0] != '%') continue;
        if (numWeap == 100) throw std::runtime_error("Too many weapons");
        if (!line.empty() && line.back() == '\\r') line.pop_back();
        if (line.size() < 2 || line.size() > 30) throw std::runtime_error("Invalid weapon name");
        auto &entry = storage[numWeap];
        std::strncpy(entry.name,line.c_str()+1,29);
        pointers[numWeap++] = &entry;
        for (int at=19; at>=0; --at) {
            if (!std::getline(input,line)) throw std::runtime_error("Incomplete weapon table");
            if (!line.empty() && line[0]=='%') line.erase(0,1);
            std::replace(line.begin(),line.end(),',',' ');
            std::istringstream row(line);
            int values[8];
            for (int &value: values) if (!(row>>value) || value<0 || value>255) throw std::runtime_error("Invalid weapon value");
            std::string extra; if (row>>extra) throw std::runtime_error("Extra weapon values");
            if(values[1]>=150 || values[0]<values[2]) throw std::runtime_error("Invalid damage slope");
            auto &column=entry.AT[at];
            column.max=values[0]; column.start=values[1]; column.min=values[2];
            for(int j=0;j<5;j++) column.crit[j]=values[j+3];
        }
    }
    if (!numWeap) throw std::runtime_error("No weapons found");
}

` +
  source.slice(end);
source = source.replace(
  "at = defUnit[U_AT];",
  "at = defUnit[U_AT] - (legacyArmor ? 0 : 1);",
);
source = source.replace(
  "w = getWeap(attackSet,unitSet);",
  'w = getWeap(attackSet,unitSet);\n   if (w < 0) throw std::runtime_error("Unknown weapon");',
);
source = source.replaceAll(
  "unitSet[d]->putData((char*)&mr,U_MC);",
  "{ char status[2] = {static_cast<char>(mr), 0}; unitSet[d]->putData(status,U_MC); }",
);
fs.writeFileSync(
  "core/resolver.cpp",
  "// Retained WARCOM 2.3.1 engine; generated by scripts/extract-core.mjs.\n" +
    source,
);
let fields = fs.readFileSync("legacy/TEST.HPP", "utf8");
fields = fields
  .slice(fields.indexOf("#define U_NAME"))
  .replaceAll("NAN", "INVALID_NUMBER");
fs.writeFileSync("core/fields.hpp", "#pragma once\n" + fields);
