// Regenerates src/data/weapons-dat.ts from legacy/WEAPONS.DAT (the untouched original).
import { readFileSync, writeFileSync } from 'node:fs';
const raw = readFileSync(new URL('../legacy/WEAPONS.DAT', import.meta.url)).toString('latin1');
writeFileSync(
  new URL('../src/data/weapons-dat.ts', import.meta.url),
  '// Generated by tools/gen-weapons.mjs from legacy/WEAPONS.DAT - do not edit by hand.\n' +
    'export const WEAPONS_DAT = ' + JSON.stringify(raw) + ';\n',
);
console.log('weapons-dat.ts written,', raw.length, 'bytes');
