// Extracts the critical-casualty and critical-damage tables from the original
// RESOLVE.CPP so they are never retyped by hand. Output: src/engine/tables.ts
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(new URL('../legacy/RESOLVE.CPP', import.meta.url), 'latin1');
const names = [
  ['critTable', 'CRIT_CASUALTY'],
  ['magicCritTable', 'MAGIC_CRIT_CASUALTY'],
  ['holyCritTable', 'HOLY_CRIT_CASUALTY'],
  ['slayCritTable', 'SLAY_CRIT_CASUALTY'],
  ['critDam', 'CRIT_DAMAGE'],
  ['magicCritDam', 'MAGIC_CRIT_DAMAGE'],
  ['holyCritDam', 'HOLY_CRIT_DAMAGE'],
  ['slayCritDam', 'SLAY_CRIT_DAMAGE'],
];

let out = `// Generated by tools/gen-tables.mjs from legacy/RESOLVE.CPP - do not edit by hand.
//
// Rows are indexed by target size class (sizeMod):
//   0 small, 1 normal, 2 type I, 3 type II, 4 large, 5 super-large, 6 no stun.
// Columns are critical severity E, D, C, B, A.

export type CritTable = readonly (readonly [number, number, number, number, number])[];

`;
for (const [cName, tsName] of names) {
  const m = new RegExp(`int\\s+${cName}\\[7\\]\\[5\\]\\s*=\\s*\\{([\\s\\S]*?)\\n\\s*\\};`).exec(src);
  if (!m) throw new Error('table not found: ' + cName);
  const rows = [...m[1].matchAll(/\{([^}]*)\}/g)].map((r) => r[1].split(',').map((n) => parseInt(n.trim(), 10)));
  if (rows.length !== 7 || rows.some((r) => r.length !== 5 || r.some(Number.isNaN))) throw new Error('bad table ' + cName);
  out += `export const ${tsName}: CritTable = [\n${rows.map((r) => `  [${r.join(', ')}],`).join('\n')}\n];\n\n`;
}
writeFileSync(new URL('../src/engine/tables.ts', import.meta.url), out.trimEnd() + '\n');
console.log('tables.ts written');
